[tool.ruff]
line-length = 79

[tool.ruff.lint]
select = ["I", "F", "W", "E"]
exclude = ["*/migrations/*", "venv"]

[tool.ruff.format]
quote-style = "single"

[tool.taskipy.tasks]
lint = "ruff check . && ruff check . --diff"
format = "ruff check . --fix && ruff format ."
