# Generated by Django 4.1 on 2025-01-28 17:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cars', '0003_car_photo_car_plate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='photo',
            field=models.ImageField(
                blank=True, default='default.png', null=True, upload_to='cars/'
            ),
        ),
    ]
