# Generated by Django 4.1 on 2025-02-13 20:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cars', '0005_alter_car_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
